# Generated by Django 4.1.4 on 2023-05-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_person_account_alter_person_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='materials',
        ),
    ]
