# Generated by Django 4.1.4 on 2023-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_person_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='materials',
            field=models.BooleanField(default=True),
        ),
    ]
