# Generated by Django 4.1.4 on 2023-05-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_rename_materials_person_chequebook_person_creditcard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Creditcard',
            new_name='CreditCard',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Debitcard',
            new_name='DebitCard',
        ),
    ]
