# Generated by Django 4.1.4 on 2023-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_rename_creditcard_person_creditcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ChequeBook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='CreditCard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='DebitCard',
            field=models.BooleanField(default=False),
        ),
    ]
